'use strict';

/**
 * Konstanten der Leapmotor-Integration.
 * Portiert aus custom_components/leapmotor/const.py des HA-Projekts.
 */

const DEFAULT_BASE_URL = 'https://appgateway.leapmotor-international.de';
const DEFAULT_APP_VERSION = '1.12.3';
const DEFAULT_DEVICE_ID = 'bd605e5c599944efb846bcf70f1449d8';
const DEFAULT_SOURCE = 'leapmotor';
const DEFAULT_CHANNEL = '1';
const DEFAULT_LANGUAGE = 'en-GB';
const DEFAULT_DEVICE_TYPE = '1';
const DEFAULT_P12_ENC_ALG = '1';
const DEFAULT_OPERPWD_AES_KEY = 'f1cf0c025baec0e2';
const DEFAULT_OPERPWD_AES_IV = '6b6a1fe94e133fd7';
const DEFAULT_POLICY_ID = '20260204';

const DEFAULT_SCAN_INTERVAL_MINUTES = 5;
const DEFAULT_ECO_SCAN_INTERVAL_MINUTES = 15;
const DEFAULT_STATE_STALE_SECONDS = 900;
const REMOTE_ACTION_COOLDOWN_SECONDS = 10;

// Aktionsschlüssel für die Fernsteuerung
const REMOTE_CTL_LOCK = 'lock';
const REMOTE_CTL_UNLOCK = 'unlock';
const REMOTE_CTL_UNLOCK_CHARGER = 'unlock_charger';
const REMOTE_CTL_TRUNK = 'trunk';
const REMOTE_CTL_TRUNK_OPEN = 'trunk_open';
const REMOTE_CTL_TRUNK_CLOSE = 'trunk_close';
const REMOTE_CTL_FIND_CAR = 'find_car';
const REMOTE_CTL_SUNSHADE = 'sunshade';
const REMOTE_CTL_SUNSHADE_OPEN = 'sunshade_open';
const REMOTE_CTL_SUNSHADE_CLOSE = 'sunshade_close';
const REMOTE_CTL_BATTERY_PREHEAT = 'battery_preheat';
const REMOTE_CTL_BATTERY_PREHEAT_OFF = 'battery_preheat_off';
const REMOTE_CTL_STEERING_WHEEL_HEAT_ON = 'steering_wheel_heat_on';
const REMOTE_CTL_STEERING_WHEEL_HEAT_OFF = 'steering_wheel_heat_off';
const REMOTE_CTL_REARVIEW_MIRROR_HEAT_ON = 'rearview_mirror_heat_on';
const REMOTE_CTL_REARVIEW_MIRROR_HEAT_OFF = 'rearview_mirror_heat_off';
const REMOTE_CTL_SEAT_HEAT = 'seat_heat';
const REMOTE_CTL_SEAT_VENTILATION = 'seat_ventilation';
const REMOTE_CTL_WINDOWS = 'windows';
const REMOTE_CTL_WINDOWS_OPEN = 'windows_open';
const REMOTE_CTL_WINDOWS_CLOSE = 'windows_close';
const REMOTE_CTL_AC_SWITCH = 'ac_switch';
const REMOTE_CTL_AC_ON = 'ac_on';
const REMOTE_CTL_AC_OFF = 'ac_off';
const REMOTE_CTL_QUICK_COOL = 'quick_cool';
const REMOTE_CTL_QUICK_HEAT = 'quick_heat';
const REMOTE_CTL_WINDSHIELD_DEFROST = 'windshield_defrost';

module.exports = {
    DEFAULT_BASE_URL,
    DEFAULT_APP_VERSION,
    DEFAULT_DEVICE_ID,
    DEFAULT_SOURCE,
    DEFAULT_CHANNEL,
    DEFAULT_LANGUAGE,
    DEFAULT_DEVICE_TYPE,
    DEFAULT_P12_ENC_ALG,
    DEFAULT_OPERPWD_AES_KEY,
    DEFAULT_OPERPWD_AES_IV,
    DEFAULT_POLICY_ID,
    DEFAULT_SCAN_INTERVAL_MINUTES,
    DEFAULT_ECO_SCAN_INTERVAL_MINUTES,
    DEFAULT_STATE_STALE_SECONDS,
    REMOTE_ACTION_COOLDOWN_SECONDS,
    REMOTE_CTL_LOCK,
    REMOTE_CTL_UNLOCK,
    REMOTE_CTL_UNLOCK_CHARGER,
    REMOTE_CTL_TRUNK,
    REMOTE_CTL_TRUNK_OPEN,
    REMOTE_CTL_TRUNK_CLOSE,
    REMOTE_CTL_FIND_CAR,
    REMOTE_CTL_SUNSHADE,
    REMOTE_CTL_SUNSHADE_OPEN,
    REMOTE_CTL_SUNSHADE_CLOSE,
    REMOTE_CTL_BATTERY_PREHEAT,
    REMOTE_CTL_BATTERY_PREHEAT_OFF,
    REMOTE_CTL_STEERING_WHEEL_HEAT_ON,
    REMOTE_CTL_STEERING_WHEEL_HEAT_OFF,
    REMOTE_CTL_REARVIEW_MIRROR_HEAT_ON,
    REMOTE_CTL_REARVIEW_MIRROR_HEAT_OFF,
    REMOTE_CTL_SEAT_HEAT,
    REMOTE_CTL_SEAT_VENTILATION,
    REMOTE_CTL_WINDOWS,
    REMOTE_CTL_WINDOWS_OPEN,
    REMOTE_CTL_WINDOWS_CLOSE,
    REMOTE_CTL_AC_SWITCH,
    REMOTE_CTL_AC_ON,
    REMOTE_CTL_AC_OFF,
    REMOTE_CTL_QUICK_COOL,
    REMOTE_CTL_QUICK_HEAT,
    REMOTE_CTL_WINDSHIELD_DEFROST,
};
